apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::900035554061:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XVD7UAGPA01E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::900035554061:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-23T14:54:56Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-23T14:54:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1568"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c7da7752-a732-4c99-a29e-97f60e19f750
